services:
  - type: web
    name: telegram-bot-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    plan: free
    autoDeploy: true
